name: Test & Build

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Run Tests...
        run: go test -v -vet=off -race ./...
      - name: Build...
        run: go build -race cmd/killgrave/main.go
